import howItWorksIllustration from "../images/how-it-works.jpg";
import { Col, Container, Row } from "react-bootstrap";
import { Divider, Typography } from "@mui/material";
import Card from "@mui/material/Card";

export const HowItWorks = () => {
  const keyFactors = [
    {
      headline: "How much soon hits your roof",
      description:
        "Solar systems produce less electricity on cloudy days. The great majority of homes with solar still connect to the electric grid, drawing power from the grid when needed.",
    },
    {
      headline: "How much power you consume",
      description:
        "Bigger homes, bigger savings. Multifamily homes can have bigger potential. If your power consumption is really low, it will take long before the investment returns back. ",
    },
    {
      headline: "Electricity rates",
      description:
        "Areas with higher electricity rates have better potential for more savings.",
    },
    {
      headline: "Supportive solar policies",
      description:
        "Some countries provide supportive policies to encourage building solar panels and move to green energy.",
    },
    {
      headline: "Hardware, installation, and monitoring costs",
      description:
        "Depending on what type of hardware you choose, it can lead to higher or lower savings.",
    },
  ];

  const installmentSteps = [
    {
      headline: "1. Solar panels",
      description:
        "Solar panels are made up of photovoltaic (PV) cells, which convert\n" +
        " sunlight into direct current (DC) electricity.",
    },
    {
      headline: "2. Inverter",
      description:
        "An inverter converts the DC electricity generated by solar panels\n" +
        " into the alternating current (AC) electricity used in most homes.",
    },
    {
      headline: "3. Monitoring system",
      description:
        "A monitoring system sends information about your solar installation,\n" +
        " including the amount of energy it generates, to your solar provider,\n" +
        " to maintain optimal system performance.",
    },
    {
      headline: "4. Utility grid",
      description:
        " Your solar system is still connected to a local utility grid to\n" +
        "  provide power after sundown. Connection to the grid also allows your\n" +
        "  solar system to return to the grid any excess clean energy your\n" +
        "  system generates during the day. A utility meter measures your power\n" +
        "  consumption and solar output.",
    },
  ];

  return (
    <Container style={{ opacity: 0.95, paddingBottom: "50px" }}>
      <Typography
        variant={"h3"}
        sx={{
          textAlign: "center",
          paddingTop: "70px",
          paddingBottom: "60px",
        }}
      >
        How does solar work?
      </Typography>

      <img
        src={howItWorksIllustration}
        alt={"how-it-works"}
        style={{ width: "100%" }}
      />

      <Row style={{ textAlign: "center", marginTop: "30px" }}>
        {installmentSteps.map((step, index) => (
          <Col key={index}>
            <Card sx={{ height: "285px", padding: "10px" }}>
              <Typography sx={{ my: "20px" }} variant={"h5"}>
                {step.headline}
              </Typography>
              <Typography>{step.description}</Typography>
            </Card>
          </Col>
        ))}
      </Row>

      <Row style={{ textAlign: "center" }}>
        <Typography
          variant={"h4"}
          sx={{
            paddingTop: "40px",
            paddingBottom: "40px",
          }}
        >
          Key factors for saving more
        </Typography>
      </Row>

      <Row style={{ textAlign: "center" }}>
        {keyFactors.map((factor, index) => (
          <Col key={index}>
            <Card sx={{ height: "265px", padding: "10px" }}>
              <Typography sx={{ mb: "15px", mt: "10px" }} variant={"h6"}>
                {factor.headline}
              </Typography>
              <Divider />
              <Typography sx={{ mt: "15px" }}>{factor.description}</Typography>
            </Card>
          </Col>
        ))}
      </Row>
    </Container>
  );
};
